### ISSUE TITLE
Fails to compile with GCC UPC

### ISSUE THREAD

**Issue by nickaj** [EPCCed/exaflow-exags-upc#1]
Following the instructions, fails to compile with error log:
```
In file included from fail.upc:8:0:
comm.h:121:24: error: unknown type name ‘comm_req’
 static void comm_irecv(comm_req *req, const struct comm *c,
                        ^
comm.h:123:24: error: unknown type name ‘comm_req’
 static void comm_isend(comm_req *req, const struct comm *c,
                        ^
comm.h:125:23: error: unknown type name ‘comm_req’
 static void comm_wait(comm_req *req, int n);
                       ^
comm.h: In function ‘comm_free’:
comm.h:261:5: warning: passing argument 1 of ‘upc_free’ discards ‘strict’ qualifier from pointer target type [enabled by default]
     upc_free(c->flgs);
     ^
In file included from comm.h:70:0,
                 from fail.upc:8:
/home/nick/root/lib/gcc/x86_64-unknown-linux-gnu/4.8.0/include/upc.h:114:13: note: expected ‘shared void *’ but argument is of type ‘strict shared int *’
 extern void upc_free (shared void *);
             ^
In file included from fail.upc:8:0:
comm.h: At top level:
comm.h:309:24: error: unknown type name ‘comm_req’
 static void comm_irecv(comm_req *req, const struct comm *c,
                        ^
comm.h:317:24: error: unknown type name ‘comm_req’
 static void comm_isend(comm_req *req, const struct comm *c,
                        ^
comm.h:325:23: error: unknown type name ‘comm_req’
 static void comm_wait(comm_req *req, int n)
                       ^
Makefile:382: recipe for target 'fail.o' failed
```
comm_req isn't defined unless you have the right header combo, which GCC UPC at least doesn't provide.

**Comment by njansson** [comment]
My bad, it works fine with GCC UPC 5.2.0 but 4.8.x doesn't implement the non-blocking extension of UPC 1.3

**Comment by nickaj** [comment]
@njansson The fix works with GCCUPC 4.8 and ClangUPC3.8.1.0 so please fell free to merge gupc_nb to master
